#!/bin/sh

uci add dhcp host
uci set dhcp.@host[-1].name='AX5400Pro'
uci add_list dhcp.@host[-1].mac='98:17:F1:6E:AB:50'
uci set dhcp.@host[-1].ip='192.168.1.250'
uci set dhcp.@host[-1].leasetime='infinite'
uci commit dhcp

/etc/init.d/dnsmasq reload
exit 0


