#!/bin/sh

########################
# LAN bridge
########################
uci set network.br_lan='device'
uci set network.br_lan.name='br-lan'
uci set network.br_lan.type='bridge'
uci set network.br_lan.mtu='1500'
uci set network.br_lan.mtu6='1500'

uci add_list network.br_lan.ports='eth1'
uci add_list network.br_lan.ports='eth2'
uci add_list network.br_lan.ports='eth3'

########################
# LAN interface
########################
uci set network.lan='interface'
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='60'

########################
# WAN interface（PPPoE）
########################
uci set network.wan='interface'
uci set network.wan.device='eth0'
uci set network.wan.proto='pppoe'
uci set network.wan.ipv6='auto'

########################
# 提交
########################
uci commit network
/etc/init.d/network restart



uci add dhcp host
uci set dhcp.@host[-1].name='AX5400Pro'
uci add_list dhcp.@host[-1].mac='98:17:F1:6E:AB:50'
uci set dhcp.@host[-1].ip='192.168.1.2'
uci set dhcp.@host[-1].leasetime='infinite'
uci commit dhcp

/etc/init.d/dnsmasq restart


#openclash 内核
mkdir -p /etc/openclash/core

cp /tmp/mihomo-linux-amd64-v2-* /etc/openclash/core/clash_mate
chmod 777 /etc/openclash/core/clash_mate

#nikki 内核
cp /tmp/mihomo-linux-amd64-v2-* /usr/bin/mihomo
chmod 777 /usr/bin/mihomo

exit 0


